version: '3.7'

services:
  grandet_db:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: tweb_test
      POSTGRES_USER: tweb_test
      POSTGRES_DB: tweb_db
    container_name: tweb_db
    ports:
      - 5432:5432
    volumes:
      - /tmp/tweb_db/pgdata:/var/lib/postgresql/data
  tweb:
    image: mickeyzhoudocker/tweb_prod:latest
    container_name: tweb_app
    environment: 
      TUSHARE_TOKEN: ${TUSHARE_TOKEN}
      TUSHARE_API: https://api.tushare.pro
    ports:
      - 8888:8888
    depends_on: 
      - grandet_db
    restart: always
    volumes:
      - ./conf-docker.yaml:/conf.yaml

