// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchRecordRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRecordRequest) Reset()         { *m = FetchRecordRequest{} }
func (m *FetchRecordRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRecordRequest) ProtoMessage()    {}
func (*FetchRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{0}
}

func (m *FetchRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRecordRequest.Unmarshal(m, b)
}
func (m *FetchRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRecordRequest.Marshal(b, m, deterministic)
}
func (m *FetchRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRecordRequest.Merge(m, src)
}
func (m *FetchRecordRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRecordRequest.Size(m)
}
func (m *FetchRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRecordRequest proto.InternalMessageInfo

type FetchRecordResponse struct {
	Error                Error    `protobuf:"varint,1,opt,name=error,proto3,enum=common.Error" json:"error,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRecordResponse) Reset()         { *m = FetchRecordResponse{} }
func (m *FetchRecordResponse) String() string { return proto.CompactTextString(m) }
func (*FetchRecordResponse) ProtoMessage()    {}
func (*FetchRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{1}
}

func (m *FetchRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRecordResponse.Unmarshal(m, b)
}
func (m *FetchRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRecordResponse.Marshal(b, m, deterministic)
}
func (m *FetchRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRecordResponse.Merge(m, src)
}
func (m *FetchRecordResponse) XXX_Size() int {
	return xxx_messageInfo_FetchRecordResponse.Size(m)
}
func (m *FetchRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRecordResponse proto.InternalMessageInfo

func (m *FetchRecordResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

func (m *FetchRecordResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *FetchRecordResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*FetchRecordRequest)(nil), "record.FetchRecordRequest")
	proto.RegisterType((*FetchRecordResponse)(nil), "record.FetchRecordResponse")
}

func init() { proto.RegisterFile("record.proto", fileDescriptor_bf94fd919e302a1d) }

var fileDescriptor_bf94fd919e302a1d = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0x41, 0x0b, 0x82, 0x40,
	0x10, 0x85, 0x31, 0x4b, 0x68, 0xb1, 0x88, 0xad, 0x83, 0x74, 0x12, 0xbb, 0x48, 0x07, 0x17, 0xea,
	0x1f, 0x04, 0x45, 0xe7, 0xed, 0xd6, 0x29, 0x5d, 0x87, 0x0c, 0xd3, 0xb1, 0xd9, 0xb5, 0xfe, 0x7e,
	0xb8, 0xdb, 0xa5, 0xd3, 0xbc, 0xf9, 0x1e, 0x7c, 0x3c, 0x16, 0x12, 0x28, 0xa4, 0x32, 0xeb, 0x08,
	0x0d, 0xf2, 0xc0, 0x7d, 0xeb, 0x50, 0x61, 0xd3, 0x60, 0xeb, 0x68, 0xb2, 0x62, 0xfc, 0x04, 0x46,
	0x55, 0xd2, 0x96, 0x12, 0x5e, 0x3d, 0x68, 0x93, 0xdc, 0xd8, 0xf2, 0x8f, 0xea, 0x0e, 0x5b, 0x0d,
	0x7c, 0xc3, 0x26, 0x40, 0x84, 0x14, 0x79, 0xb1, 0x97, 0xce, 0x77, 0xb3, 0xec, 0xa7, 0x3a, 0x0e,
	0x50, 0xba, 0x8e, 0x73, 0x36, 0x56, 0x58, 0x42, 0x34, 0x8a, 0xbd, 0x74, 0x2a, 0x6d, 0xe6, 0x0b,
	0xe6, 0xf7, 0xf4, 0x8c, 0x7c, 0x8b, 0x86, 0x78, 0xd8, 0x5e, 0xd3, 0xfb, 0xc3, 0x54, 0x7d, 0x31,
	0x38, 0xc4, 0xa5, 0xcd, 0x6b, 0x38, 0xe7, 0xaa, 0x06, 0x12, 0xe6, 0x03, 0x85, 0xd0, 0x40, 0x6f,
	0x20, 0x61, 0x37, 0x16, 0x81, 0x3d, 0xfb, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xf1, 0xbb,
	0xf7, 0xd0, 0x00, 0x00, 0x00,
}
